export const projects = [
  {
    name: "Learn The Web",
    description:
      "A guide to mastering web development, from basics to advanced.",
    createdAt: "2025-02-11",
    url: "https://learn-the-web.vercel.app",
    openSource: "learn-the-web",
    monthlyVisitors: 360,
    image: "/assets/learn-the-web/og-image.png",
    blogPost: "learn-the-web",
  },
  {
    name: "Snappy - LLMs Speed Test",
    description: "Benchmark your LLMs in Seconds ⚡",
    createdAt: "2025-01-23",
    url: "https://snappy.raulcarini.dev",
    openSource: "llms-speed-test",
    monthlyVisitors: 60,
    image: "/assets/llms-speed-test/og-image.png",
    blogPost: "llms-speed-test",
  },
  {
    name: "Texta - Editor",
    description: "Create blogging content with ease ✨",
    createdAt: "2024-11-3",
    url: "https://editor.raulcarini.dev",
    openSource: "text-editor",
    monthlyVisitors: 60,
    image: "/assets/text-editor/og-image.webp",
    blogPost: "texta-editor",
  },
  {
    name: "Tailwind CSS Colors",
    description: "Tailwind CSS colors in HSL, RGB, and HEX formats.",
    createdAt: "2024-10-17",
    url: "https://colors.raulcarini.dev",
    openSource: "tailwind-color-palette",
    monthlyVisitors: 188,
    image: "/assets/tailwind-color-palette/og-image.png",
    blogPost: "tailwindcss-color-palettes",
  },
  {
    name: "Spotify Web Player",
    description: "Listen to your Music Anytime, Anywhere.",
    createdAt: "2024-09-29",
    url: "https://web-player.raulcarini.dev",
    openSource: "spotify-web-player",
    monthlyVisitors: 40,
    image: "/assets/spotify-web-player/og-image.png",
    blogPost: "spotify-web-player",
  },
  {
    name: "Live Map",
    description:
      "A world map with stats and general information for each country.",
    createdAt: "2024-09-15",
    url: "https://maps.raulcarini.dev",
    openSource: "live-map",
    monthlyVisitors: 0,
    image: "/assets/live-map/home.png",
    blogPost: "live-map",
  },
  {
    name: "Archive Space",
    description: "A simple archive with Cloudflare R2.",
    createdAt: "2024-08-11",
    url: "https://archive.raulcarini.dev",
    openSource: "archive-space",
    monthlyVisitors: 0,
    image: "/assets/archive-space/home.png",
    blogPost: "archive-space",
  },
  {
    name: "My Portfolio",
    description: "A simple design portfolio and blog made with NextJs and MDX.",
    createdAt: "2024-04-21",
    url: "https://raulcarini.dev",
    openSource: "raulcarini.com-v2",
    monthlyVisitors: 110,
    image: "/assets/portfolio/home.png",
    blogPost: "raulcarini-dev",
  },
  {
    name: "PedeBeats Kits",
    description: "A e-commerce website for selling drum kits.",
    createdAt: "2023-12-10",
    url: "https://kits.pedebeats.com",
    monthlyVisitors: 3050,
  },
  {
    name: "Shortly",
    description:
      "A simple URL shortening service. Made with Next.js and MongoDB.",
    createdAt: "2023-08-17",
    url: "https://shrly.cc",
    monthlyVisitors: 20,
    image: "/assets/shortly/home-page.png",
    moneyEarned: 0,
    blogPost: "shortly",
  },
];
